"""Observability and tracing with Langfuse.

This module contains:
- Trace configuration
- Custom metrics and metadata
- Cost attribution and tracking
- Dashboard utilities
- Nested span hierarchy support
- Tagging system for categorization
- Failure analysis and alerting
"""

from src.observability.costs import (
    AlertSeverity,
    CostAlert,
    CostAlertManager,
    CostBreakdown,
    CostReport,
    CostThresholds,
    CostTracker,
    ModelPricing,
    ModelProvider,
    TokenUsage,
    calculate_llm_cost,
    estimate_request_cost,
    format_cost,
    generate_cost_report,
    get_cost_tracker,
    get_model_pricing,
    reset_cost_tracker,
)
from src.observability.metrics import (
    AgentMetadata,
    MetadataBuilder,
    RequestMetadata,
    Tag,
    TagManager,
    ToolMetadata,
    collect_tags,
    create_agent_metadata,
    create_request_metadata,
    create_tool_metadata,
)
from src.observability.dashboards import (
    AggregationType,
    DashboardConfig,
    DashboardPanel,
    DashboardService,
    DashboardSnapshot,
    MetricCollector,
    MetricDataPoint,
    MetricDefinition,
    MetricType,
    PanelType,
    TimeWindow,
    create_agent_dashboard,
    create_all_dashboards,
    create_cost_dashboard,
    create_error_dashboard,
    create_overview_dashboard,
    get_dashboard_service,
    get_metric_collector,
    reset_dashboard_service,
)
from src.observability.failures import (
    FailureAlert,
    FailureAlertManager,
    FailureAlertThresholds,
    FailureAlertType,
    FailureAnalysis,
    FailureCategory,
    FailureCategorizer,
    FailurePattern,
    FailureRecord,
    FailureReport,
    FailureSeverity,
    FailureTracker,
    PatternDetector,
    generate_failure_report,
    get_failure_alert_manager,
    get_failure_tracker,
    reset_failure_tracking,
)
from src.observability.tracing import (
    SpanContext,
    SpanLevel,
    SpanMetadata,
    TraceContext,
    agent_span,
    flush_traces,
    generation_span,
    get_langfuse_client,
    planning_span,
    postprocessing_span,
    preprocessing_span,
    request_span,
    shutdown_tracing,
    tool_span,
    traced_agent,
    traced_generation,
    traced_tool,
)
from src.observability.replay import (
    CapturedSpan,
    CapturedToolResponse,
    ComparisonEngine,
    ReplayableRequest,
    ReplayComparison,
    ReplayEngine,
    ReplayMode,
    ReplayResult,
    ReplayStatus,
    ReplayStepResult,
    ToolMockManager,
    TraceRetriever,
    capture_and_replay,
    create_replay_report,
)

__all__ = [
    # Cost tracking classes
    "AlertSeverity",
    "CostAlert",
    "CostAlertManager",
    "CostBreakdown",
    "CostReport",
    "CostThresholds",
    "CostTracker",
    "ModelPricing",
    "ModelProvider",
    "TokenUsage",
    # Cost functions
    "calculate_llm_cost",
    "estimate_request_cost",
    "format_cost",
    "generate_cost_report",
    "get_cost_tracker",
    "get_model_pricing",
    "reset_cost_tracker",
    # Metadata classes
    "AgentMetadata",
    "MetadataBuilder",
    "RequestMetadata",
    "Tag",
    "TagManager",
    "ToolMetadata",
    # Metadata factory functions
    "collect_tags",
    "create_agent_metadata",
    "create_request_metadata",
    "create_tool_metadata",
    # Span hierarchy classes
    "SpanContext",
    "SpanLevel",
    "SpanMetadata",
    # Convenience span functions
    "agent_span",
    "generation_span",
    "planning_span",
    "postprocessing_span",
    "preprocessing_span",
    "request_span",
    "tool_span",
    # Trace context and decorators
    "TraceContext",
    "traced_agent",
    "traced_generation",
    "traced_tool",
    # Client utilities
    "flush_traces",
    "get_langfuse_client",
    "shutdown_tracing",
    # Dashboard classes
    "AggregationType",
    "DashboardConfig",
    "DashboardPanel",
    "DashboardService",
    "DashboardSnapshot",
    "MetricCollector",
    "MetricDataPoint",
    "MetricDefinition",
    "MetricType",
    "PanelType",
    "TimeWindow",
    # Dashboard factory functions
    "create_agent_dashboard",
    "create_all_dashboards",
    "create_cost_dashboard",
    "create_error_dashboard",
    "create_overview_dashboard",
    # Dashboard utilities
    "get_dashboard_service",
    "get_metric_collector",
    "reset_dashboard_service",
    # Failure analysis classes
    "FailureAlert",
    "FailureAlertManager",
    "FailureAlertThresholds",
    "FailureAlertType",
    "FailureAnalysis",
    "FailureCategory",
    "FailureCategorizer",
    "FailurePattern",
    "FailureRecord",
    "FailureReport",
    "FailureSeverity",
    "FailureTracker",
    "PatternDetector",
    # Failure analysis functions
    "generate_failure_report",
    "get_failure_alert_manager",
    "get_failure_tracker",
    "reset_failure_tracking",
    # Replay system classes
    "CapturedSpan",
    "CapturedToolResponse",
    "ComparisonEngine",
    "ReplayableRequest",
    "ReplayComparison",
    "ReplayEngine",
    "ReplayMode",
    "ReplayResult",
    "ReplayStatus",
    "ReplayStepResult",
    "ToolMockManager",
    "TraceRetriever",
    # Replay functions
    "capture_and_replay",
    "create_replay_report",
]
